baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Ewerton de Oliveira](https://www.linkedin.com/in/ewerlopes/) 2019 -- {Year} | [Github](https://github.com/ewerlopes) | [Twitter](https://twitter.com/ewerlopes)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
