baseURL = 'https://ewerlopes.github.io/'
locale = 'en-us'
theme = 'mytheme'
title = 'Half-bayesianism'
publishDir = '../docs'

[markup]
  [markup.goldmark.renderer]
    unsafe = true

# Navigation
[menu]
    [[menu.main]]
        name = "posts"
        url = "/posts/"
        weight = 1

    [[menu.main]]
        name = "about"
        url = "/about"
        weight = 2

    [[menu.main]]
        name = "tags"
        url = "/tags/"
        weight = 3

    [[menu.main]]
        name = "categories"
        url = "/categories/"
        weight = 4
